### PR TITLE
Fixes #4697 Do not try to create invalid runes e.g. surrogate pair secondary parts

### LINKED ISSUE #4697: Scrolling far enough down TableEditor Char Map scenario causes crash
It crashes at RepresentationGetter so may just be that you are enumerating something the other doesn't until it scrolls into view...

The error is around:
```
new Rune ((uint)o).ToString ()
o is 55299
```
So bombing in Run constructor I think which means its likely unrelated to your code and if you scroll down far enough on v2_develop it will also crash.

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. (Parameter 'value')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Text.Rune..ctor(UInt32 value)
   at UICatalog.Scenarios.TableEditor.<>c.<BuildUnicodeMap>b__13_0(Object o) in D:\Repos\temp\gui.cs\Examples\UICatalog\Scenarios\TableEditor.cs:line 568
   at Terminal.Gui.Views.ColumnStyle.GetRepresentation(Object value) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\ColumnStyle.cs:line 107
   at Terminal.Gui.Views.TableView.GetRepresentation(Object value, ColumnStyle colStyle) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\TableView.cs:line 922
   at Terminal.Gui.Views.TableView.CalculateMaxCellWidth(Int32 col, ColumnStyle colStyle) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\TableView.cs:line 659
   at Terminal.Gui.Views.TableView.CalculateContentSize() in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\TableView.cs:line 828
   at Terminal.Gui.Views.TableView.RefreshContentSize() in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\TableView.Navigation.cs:line 37
   at Terminal.Gui.Views.TableView.set_Table(ITableSource value) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TableView\TableView.Navigation.cs:line 25
   at UICatalog.Scenarios.TableEditor.SetTable(DataTable dataTable) in D:\Repos\temp\gui.cs\Examples\UICatalog\Scenarios\TableEditor.cs:line 948
   at UICatalog.Scenarios.TableEditor.OpenUnicodeMap() in D:\Repos\temp\gui.cs\Examples\UICatalog\Scenarios\TableEditor.cs:line 823
   at Terminal.Gui.Views.Shortcut.DispatchCommand(ICommandContext commandContext) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\Shortcut.cs:line 307
   at Terminal.Gui.Views.MenuItem.DispatchCommand(ICommandContext commandContext) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\Menu\MenuItem.cs:line 142
   at Terminal.Gui.ViewBase.View.InvokeCommand(Command command, IInputBinding binding) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Command.cs:line 476
   at Terminal.Gui.ViewBase.View.InvokeCommands(Command[] commands, IInputBinding binding) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Command.cs:line 442
   at Terminal.Gui.ViewBase.View.InvokeCommandsBoundToKey(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Keyboard.cs:line 599
   at Terminal.Gui.ViewBase.View.NewKeyDownEvent(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Keyboard.cs:line 462
   at Terminal.Gui.ViewBase.View.NewKeyDownEvent(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Keyboard.cs:line 448
   at Terminal.Gui.ViewBase.View.NewKeyDownEvent(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\ViewBase\View.Keyboard.cs:line 448
   at Terminal.Gui.App.ApplicationPopover.DispatchKeyDown(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\App\ApplicationPopover.cs:line 204
   at Terminal.Gui.App.KeyboardImpl.RaiseKeyDownEvent(Key key) in D:\Repos\temp\gui.cs\Terminal.Gui\App\Keyboard\KeyboardImpl.cs:line 167
   at Terminal.Gui.App.ApplicationImpl.Driver_KeyDown(Object sender, Key e) in D:\Repos\temp\gui.cs\Terminal.Gui\App\ApplicationImpl.Driver.cs:line 198
   at Terminal.Gui.Drivers.DriverImpl.<.ctor>b__0_0(Object s, Key e) in D:\Repos\temp\gui.cs\Terminal.Gui\Drivers\DriverImpl.cs:line 50
   at Terminal.Gui.Drivers.InputProcessorImpl`1.RaiseKeyDownEvent(Key a) in D:\Repos\temp\gui.cs\Terminal.Gui\Drivers\Input\InputProcessorImpl.cs:line 238
   at Terminal.Gui.Drivers.InputProcessorImpl`1.ProcessAfterParsing(TInputRecord input) in D:\Repos\temp\gui.cs\Terminal.Gui\Drivers\Input\InputProcessorImpl.cs:line 165
   at Terminal.Gui.Drivers.WindowsInputProcessor.Process(InputRecord inputEvent) in D:\Repos\temp\gui.cs\Terminal.Gui\Drivers\WindowsDriver\WindowsInputProcessor.cs:line 47
   at Terminal.Gui.Drivers.InputProcessorImpl`1.ProcessQueue() in D:\Repos\temp\gui.cs\Terminal.Gui\Drivers\Input\InputProcessorImpl.cs:line 102
   at Terminal.Gui.App.ApplicationMainLoop`1.IterationImpl() in D:\Repos\temp\gui.cs\Terminal.Gui\App\MainLoop\ApplicationMainLoop.cs:line 138
   at Terminal.Gui.App.ApplicationMainLoop`1.Iteration() in D:\Repos\temp\gui.cs\Terminal.Gui\App\MainLoop\ApplicationMainLoop.cs:line 122
   at Terminal.Gui.App.MainLoopCoordinator`1.RunIteration() in D:\Repos\temp\gui.cs\Terminal.Gui\App\MainLoop\MainLoopCoordinator.cs:line 97
   at Terminal.Gui.App.ApplicationImpl.RunLoop(IRunnable runnable, Func`2 errorHandler) in D:\Repos\temp\gui.cs\Terminal.Gui\App\ApplicationImpl.Run.cs:line 266
   at Terminal.Gui.App.ApplicationImpl.Run(IRunnable runnable, Func`2 errorHandler) in D:\Repos\temp\gui.cs\Terminal.Gui\App\ApplicationImpl.Run.cs:line 237
   at UICatalog.Scenarios.TableEditor.Main() in D:\Repos\temp\gui.cs\Examples\UICatalog\Scenarios\TableEditor.cs:line 320
   at UICatalog.Runner.RunScenario(String scenarioName, Boolean benchmark) in D:\Repos\temp\gui.cs\Examples\UICatalog\Runner.cs:line 61
   at UICatalog.Runner.RunInteractive[T](Boolean enableConfigWatcher) in D:\Repos\temp\gui.cs\Examples\UICatalog\Runner.cs:line 270
   at UICatalog.UICatalog.UICatalogMain(UICatalogCommandLineOptions options) in D:\Repos\temp\gui.cs\Examples\UICatalog\UICatalog.cs:line 318
   at UICatalog.UICatalog.Main(String[] args) in D:\Repos\temp\gui.cs\Examples\UICatalog\UICatalog.cs:line 205

```

_Originally posted by @tznind in https://github.com/gui-cs/Terminal.Gui/issues/4691#issuecomment-3866985487_

### PR DESCRIPTION
**Pull request by tznind**
## Fixes

- Fixes #4697 

## Proposed Changes/Todos

This scenario shows all unicode chars.  It naievely turns all ints to unicode and shows them.  But dotnet crashes on some of them because they are not valid Runes e.g. surrogate pair latter halves.

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [ ] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [ ] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [ ] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any poor grammar or misspellings
- [ ] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tznind** [comment]
Test failure unrelated to changes?

**Comment by BDisp** [comment]
> Test failure unrelated to changes?

No, don't worry. It happens sporadically. Macs with ARM64 handle timers differently than x64, and sometimes collisions occur under race conditions.

File: Examples/UICatalog/Scenarios/TableEditor.cs [hunk 1]
```diff
@@ -602,6 +603,15 @@ private DataTable BuildUnicodeMap ()
         return dt;
     }
 
+    private string RuneToString (object o)
```
Comment (BDisp) [inline Examples/UICatalog/Scenarios/TableEditor.cs:606]: I recommend using grapheme clusters from the Cell class instead of runes, as it handles various types of rune combinations much better, including a surrogate pair combined with another surrogate pair linked by ZWJ (Zero Width Joiner). This way, these combinations can occupy only 2 columns instead of 4 or 5, depending on the terminal type.

Comment (tznind) [reply Examples/UICatalog/Scenarios/TableEditor.cs:606]: Can you show suggested code?

This is scenario

Each table entry is supposed to be 1 Rune 

It teats that table view sizes columns correctly

Strings are what our users deal with so it has to remain the return type.

But if you have a better way to enumerate all renderable unicode sequences/values. Then Id like it.

Comment (BDisp) [reply Examples/UICatalog/Scenarios/TableEditor.cs:606]: A grapheme always returns a string. But since RepresentationGetter normally send a number representing the code point, your code is fine. OpenCharacterMap occasionally throws an exception, but I haven't figured it out yet.

Comment (BDisp) [reply Examples/UICatalog/Scenarios/TableEditor.cs:606]: The exception "Cannot cast object of type 'System.String' to type 'System.UInt32'." typically occurs when the OpenCharacterMap example is open and then you press the F4 key, which will open the OpenSimple example. The parameter `o` normally has a value of type "R0C0" which is information from the OpenSimple example.

The following amendment resolves the exception.

```cs
    private static string RuneToString (object o)
    {
        try
        {
            if (o is uint i && Rune.TryCreate (i, out Rune rune))
            {
                return rune.ToString ();
            }

            return (string)o;
        }
        catch
        {
            return " ";
        }
    }
```
