### PR TITLE
Fixes #4391. Weird situation where ForceDriver with args doesn't persists on open scenario

### LINKED ISSUE #4391: Weird situation when DotNetDriver is running and then open any scenario the WindowsDriver or UnixDriver runs
## Describe the bug

**On Windows:**
- When `DotNetDriver` is running, opening any scenario cause the `WindowsDriver` to run.

**On Linux and macOS:**
- When `DotNetDriver` is running, opening any scenario cause the `UnixDriver` to run.

## To Reproduce

- Run DotNetDriver
- Put a breakpoint in the NetInput Peek method
- The breakpoint is hit, so DotNetDriver is running
- Open any scenario
- Put a breakpoint in the NetInput Peek method
- The breakpoint is not hit, so DotNetDriver is not running
- Put a breakpoint in the WindowsInput or UnixInput Peek method
- The breakpoint is hit, so WindowsDriver or UnixInput is running

2. Expected behavior: (describe what should happen)

When opening a scenario the current `DotNetDriver` instance is disposed and a new `DotNetDriver` is initialized.

3. Actual behavior: (describe what actually happens)

**On Windows:**
- When opening a scenario the current `DotNetDriver` instance is disposed and a new `WindowsDriver` is initialized.

**On Linux and macOS:**
- When opening a scenario the current `DotNetDriver` instance is disposed and a new `UnixDriver` is initialized.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #4391

## Proposed Changes/Todos

- [x] Added unit test that prove the issue
- [x] Added testing code in UICatalog to allow unit test being processed
- [x] Fix ForceDriver property to not change if an exist value already exist

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
I really shouldn't have asked to make this testable. Sorry about all the trouble and complexity it caused. 

The fix is clear and obvious. If you're ok with pulling out all the test stuff I'd be ok with that.

**Comment by BDisp** [comment]
> I really shouldn't have asked to make this testable. Sorry about all the trouble and complexity it caused.
> 
No problem, we only arrive at some conclusion and experience through doing it.

> The fix is clear and obvious. If you're ok with pulling out all the test stuff I'd be ok with that.

If you're referring to creating the Run method in the UICatalog class and its unit test, I can remove that code. In fact, simply adding a Debug.Assertion of the current driver before and after opening a scenario in UICatalog is sufficient to verify that it's correct.

File: Examples/UICatalog/UICatalog.cs [hunk 1]
```diff
@@ -55,13 +55,31 @@ namespace UICatalog;
...
+    private static string? _scenarioDriver;
 
     public static string LogFilePath { get; set; } = string.Empty;
     public static LoggingLevelSwitch LogLevelSwitch { get; } = new ();
     public const string LOGFILE_LOCATION = "logs";
     public static UICatalogCommandLineOptions Options { get; set; }
 
+    public static (string? UiCatalogDriver, string? ScenarioDriver) Run (string [] args)
+    {
+        // Flag for testing
```
Comment (tig) [inline Examples/UICatalog/UICatalog.cs]: Yea. Can we get rid off all this?

**Review by tig — CHANGES_REQUESTED** [review]
