### PR TITLE
Fixes #4734: Fix unbounded memory growth in OutputBase._lastOutputStringBuilder

### LINKED ISSUE #4734: Memory leak? Nested `StringBuilder` instances keep piling up
## Describe the bug

Memory leak due to chained `StringBuilder` instances that never get cleaned up.

Assuming this is a bug in `Terminal.GUI` and not bad implementation on my part, this makes `Terminal.GUI` unsuitable for long-running TUI apps in its current state.

## To Reproduce

1. Run the following code: [https://github.com/omurad/LeakyGUI/](https://github.com/omurad/LeakyGUI/)

2. Expected behavior: `StringBuilder` instances get cleaned up once they are no longer needed

3. Actual behavior: A massive chain of nested `StringBuilder` instances grows without any cleanup/GC.

## Environment

Please run the following commands in your terminal and paste the output:

### OS Information

**Windows (PowerShell):**
```powershell
"OS: $(Get-CimInstance Win32_OperatingSystem | Select-Object -ExpandProperty Caption) $(Get-CimInstance Win32_OperatingSystem | Select-Object -ExpandProperty Version)"
```

**macOS/Linux:**
```bash
echo "OS: $(uname -s) $(uname -r)"
```

**Output:**
```
# Windows
OS: Microsoft Windows 11 Pro 10.0.26200

# Linux
OS: Linux 6.12.69+deb13-cloud-amd64
```

### Terminal Information

**Windows Terminal:**
```powershell
"Terminal: Windows Terminal $(Get-AppxPackage -Name Microsoft.WindowsTerminal | Select-Object -ExpandProperty Version)"
```

**Other terminals:**
```bash
echo $TERM
```

**Output:**
```
(paste output here)
```

### PowerShell Version

```powershell
$PSVersionTable.PSVersion
```

**Output:**
```
# Windows Terminal
Terminal: Windows Terminal 1.23.20211.0

# Windows PowerShell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      5      4

# Linux $TERM
xterm-256color
```

### .NET Information

```bash
dotnet --version
dotnet --info
```

**Output:**
```
# Windows
10.0.103
.NET SDK:
 Version:           10.0.103
 Commit:            c2435c3e0f
 Workload version:  10.0.100-manifests.c992be6d
 MSBuild version:   18.0.11+c2435c3e0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26200
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.103\

.NET workloads installed:
 [wasm-tools]
   Installation Source: VS 18.3.11512.155
   Manifest Version:    10.0.103/10.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.workload.mono.toolchain.current\10.0.103\WorkloadManifest.json
   Install Type:              Msi

Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.3
  Architecture: x64
  Commit:       c2435c3e0f

.NET SDKs installed:
  9.0.311 [C:\Program Files\dotnet\sdk]
  10.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 10.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

# Linux
10.0.103
.NET SDK:
 Version:           10.0.103
 Commit:            c2435c3e0f
 Workload version:  10.0.100-manifests.a62d7899
 MSBuild version:   18.0.11+c2435c3e0

Runtime Environment:
 OS Name:     debian
 OS Version:  13
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/10.0.103/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.3
  Architecture: x64
  Commit:       c2435c3e0f

.NET SDKs installed:
  10.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### Terminal.Gui Version

**Option 1 - Run UICatalog (easiest):**

UICatalog displays the Terminal.Gui version in its About box and status bar.

```bash
dotnet run --project Examples/UICatalog/UICatalog.csproj
```

**Option 2 - NuGet Package Version:**
```
(e.g., 2.0.0-alpha.1, 2.0.0-develop.123, etc.)
```

**Option 3 - Building from source:**
```bash
git rev-parse HEAD
git describe --tags --always --dirty
```

**Version:**
```
2.0.0-alpha.4170
```

## Screenshots, GIFs, or Terminal Output

If applicable, add screenshots, animated GIFs, or copy/paste terminal output to help explain your problem.

**Animated GIFs are especially helpful for showing behavior!**

- **Windows**: [ShareX](https://getsharex.com/) (free, captures screen to GIF)
- **macOS**: [Kap](https://getkap.co/) (free, open source)
- **Linux**: [Peek](https://github.com/phw/peek) (free)

Image

**For terminal output, use code blocks:**

```
(paste terminal output here)
```

## Additional context

Add any other context about the problem here, such as:
- Does this happen consistently or intermittently?
- Did this work in a previous version?
- Are there any error messages in the console?
- Terminal configuration or settings that might be relevant?

I think the bug is here:
```
// Bug: Terminal.Gui / Drivers / Output / OutputBase.cs line 52 + 194-197
StringBuilder _lastOutputStringBuilder = new();   // never cleared
protected virtual void Write(StringBuilder output)
{
    _lastOutputStringBuilder.Append(output);      // grows forever
}
```

All three output drivers (AnsiOutput, WindowsOutput, NetOutput) call base.Write(), feeding this unbounded accumulator every render frame.

Run the demo app I put together to reproduce this: [https://github.com/omurad/LeakyGUI](https://github.com/omurad/LeakyGUI/)

## For Maintainers

**Set Project & Milestone:** If you have access, please don't forget to set the right Project and Milestone.

### PR DESCRIPTION
**Pull request by omurad**
## Fixes

- Fixes #4734

## Proposed Changes

In `OutputBase.cs`, the problem was that `_lastOutputStringBuilder` was appended to on every `Write(StringBuilder)` call but never cleared, so it grew without bound for the lifetime of the application.

The field's only purpose is to support `GetLastOutput()`, which [per its documentation](https://github.com/gui-cs/Terminal.Gui/blob/eba9bb63c85f2d22089ed485648e716648b8d9cd/Terminal.Gui/Drivers/Output/IOutput.cs#L64-L68) should return "the ANSI escape sequences and content most recently written" — not a cumulative history.

- [x] Add a `bool _clearLastOutputPending` flag in `OutputBase.cs`.
  - [x] Modify `public virtual void Write (IOutputBuffer buffer)` to set the flag to `true` at the top.
  - [x] Modify `protected virtual void Write (StringBuilder output)` to check the flag on the **first** call within a fame, and clear the `StringBuilder` + reset flag.

    The reason I used a flag instead of simply calling `_lastOutputStringBuilder.Clear()` at the top of `Write(IOutputBuffer)` is that `Write(IOutputBuffer)` can be called multiple times between when content is produced and when `GetLastOutput()` is read.

- [x] Update `Write_Virtual_Or_NonVirtual_Uses_WriteToConsole_And_Clears_Dirty_Flags` to check for the character from the **last** write.

    The original test asserted that after the **second** write, `GetLastOutput()` still contained `"A"` and `"C"` from the **first** write. That assertion only passed because of the bug — the `StringBuilder` was accumulating all output across every frame, never clearing.

Memory profiler screenshot for comparison with the one from #4734 
image

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs [hunk 1]
```diff
@@ -144,9 +144,9 @@ public void Write_Virtual_Or_NonVirtual_Uses_WriteToConsole_And_Clears_Dirty_Fla
 
         output.Write (buffer);
 
-        // Assert: both characters were written (use Contains to avoid CI side effects)
-        Assert.Contains ("A", output.GetLastOutput ());
-        Assert.Contains ("C", output.GetLastOutput ());
+        // Assert: only the most recently written frame is captured (not accumulated history)
+        Assert.Contains ("X", output.GetLastOutput ());
+        Assert.DoesNotContain ("A", output.GetLastOutput ());
```
Comment (BDisp) [inline Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs:164]: Would it also be appropriate to include the following?
```cs
Assert.DoesNotContain ("C", output.GetLastOutput ());
```

Comment (omurad) [reply Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs:164]: Good catch, yes this will catch future regressions.

File: Terminal.Gui/Terminal.Gui.sln [hunk 2]
```diff
@@ -1,9 +1,13 @@
...
-VisualStudioVersion = 17.5.2.0
+# Visual Studio Version 18
+VisualStudioVersion = 18.3.11512.155 d18.3
 MinimumVisualStudioVersion = 10.0.40219.1
 Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Terminal.Gui", "Terminal.Gui.csproj", "{79692A4F-7704-552C-0EF5-40B81C4F2E81}"
 EndProject
+Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Terminal.Gui.Analyzers", "..\Terminal.Gui.Analyzers\Terminal.Gui.Analyzers.csproj", "{5C5BBB85-3AAB-6FD8-14FD-DC51F699B88B}"
+EndProject
+Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Terminal.Gui.Analyzers.Tests", "..\Terminal.Gui.Analyzers.Tests\Terminal.Gui.Analyzers.Tests.csproj", "{B8EE3B38-C040-AFBC-1FF8-E2B87B8369DD}"
+EndProject
```
Comment (BDisp) [inline Terminal.Gui/Terminal.Gui.sln]: I don't know if those projects were excluded from the solution for some reason. It's best to wait for @tig to approve the execution of the CI workflows and confirm that everything is in compliance.

Comment (omurad) [reply Terminal.Gui/Terminal.Gui.sln]: Fixed

**Review by BDisp — APPROVED** [review]

File: Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs [hunk 3]
```diff
@@ -144,9 +144,10 @@ public void Write_Virtual_Or_NonVirtual_Uses_WriteToConsole_And_Clears_Dirty_Fla
 
         output.Write (buffer);
 
-        // Assert: both characters were written (use Contains to avoid CI side effects)
-        Assert.Contains ("A", output.GetLastOutput ());
-        Assert.Contains ("C", output.GetLastOutput ());
+        // Assert: only the most recently written frame is captured (not accumulated history)
```
Comment (tig) [inline Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs]: Could you please separate this out into a very tight test instead of making this test more complicated? Unit tests are supposed to be as focused as possible on specifci units of functionality. Unfortunately, in this project we've not done a great job of honoring that over time and I'm pushing really hard to change that moving forward. 

Thanks!

**Review by tig — CHANGES_REQUESTED** [review]
Thank you SO MUCH for a) finding and reporting this (with an excellent Issue post), and b) creating this PR with an elegant fix. 

Please see my request below.

File: Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs (hunk 3 above)
Comment (omurad) [reply Tests/UnitTestsParallelizable/Drivers/Output/OutputBaseTests.cs]: Moved test into `GetLastOutput_Returns_Only_Most_Recent_Frame`
